package com.githubrequests.api.model

import java.io.Serializable

data class GithubPullRequestsResponse(
    var url: String = "",
    var id: Long = -1,
    var node_id: String = "",
    var html_url: String = "",
    var diff_url: String = "",
    var patch_url: String = "",
    var issue_url: String = "",
    var state: String = "",
    var number: Int = -1,
    var locked: Boolean = false,
    var title: String? = "",
    var user: User? = null,
    var body: String? = "",
    var created_at: String? = "",
    var updated_at: String? = "",
    var closed_at: String? = "",
    var merged_at: String? = "",
    var merge_commit_sha: String = "",
    var assignee: Any? = null,
    var assignees: List<Any>? = null,
    var requested_reviewers: List<Any>? = null,
    var requested_teams: List<Any>? = null,
    var labels: List<Any>? = null,
    var milestone: Any? = null,
    var draft: Boolean = false,
    var commits_url: String = "",
    var review_comments_url: String = "",
    var review_comment_url: String = "",
    var comments_url: String = "",
    var statuses_url: String = "",
    var head: Head? = null,
    var base: Head? = null,
    var _links: Links? = null,
    var author_association: String = "",
    var auto_merge: Any? = null,
    var active_lock_reason: Any? = null
) : Serializable

data class User(
    var login: String = "",
    var id: Long = -1,
    var node_id: String = "",
    var avatar_url: String = "",
    var gravatar_id: String = "",
    var url: String = "",
    var html_url: String = "",
    var followers_url: String = "",
    var following_url: String = "",
    var gists_url: String = "",
    var starred_url: String = "",
    var subscriptions_url: String = "",
    var organizations_url: String = "",
    var repos_url: String = "",
    var events_url: String = "",
    var received_events_url: String = "",
    var type: String = "",
    var site_admin: Boolean = false
)

data class Head(
    var label: String = "",
    var ref: String = "",
    var sha: String = "",
    var user: User? = null,
    var repo: Repo? = null,
)

data class Repo(
    var id: Long = -1,
    var node_id: String = "",
    var name: String = "",
    var full_name: String = "",
    var private: Boolean = false,
    var owner: User? = null,
    var html_url: String = "",
    var description: Any? = null,
    var fork: Boolean = false,
    var url: String = "",
    var forks_url: String = "",
    var keys_url: String = "",
    var collaborators_url: String = "",
    var teams_url: String = "",
    var hooks_url: String = "",
    var issue_events_url: String = "",
    var events_url: String = "",
    var assignees_url: String = "",
    var branches_url: String = "",
    var tags_url: String = "",
    var blobs_url: String = "",
    var git_tags_url: String = "",
    var git_refs_url: String = "",
    var trees_url: String = "",
    var statuses_url: String = "",
    var languages_url: String = "",
    var stargazers_url: String = "",
    var contributors_url: String = "",
    var subscribers_url: String = "",
    var subscription_url: String = "",
    var commits_url: String = "",
    var git_commits_url: String = "",
    var comments_url: String = "",
    var issue_comment_url: String = "",
    var contents_url: String = "",
    var compare_url: String = "",
    var merges_url: String = "",
    var archive_url: String = "",
    var downloads_url: String = "",
    var issues_url: String = "",
    var pulls_url: String = "",
    var milestones_url: String = "",
    var notifications_url: String = "",
    var labels_url: String = "",
    var releases_url: String = "",
    var deployments_url: String = "",
    var created_at: String = "",
    var updated_at: String = "",
    var pushed_at: String = "",
    var git_url: String = "",
    var ssh_url: String = "",
    var clone_url: String = "",
    var svn_url: String = "",
    var homepage: Any? = null,
    var size: Int = -1,
    var stargazers_count: Int = -1,
    var watchers_count: Int = -1,
    var language: String = "",
    var has_issues: Boolean = false,
    var has_projects: Boolean = false,
    var has_downloads: Boolean = false,
    var has_wiki: Boolean = false,
    var has_pages: Boolean = false,
    var mirror_url: Any? = null,
    var archived: Boolean = false,
    var disabled: Boolean = false,
    var open_issues_count: Int = -1,
    var license: Any? = null,
    var allow_forking: Boolean = false,
    var is_template: Boolean = false,
    var web_commit_signoff_required: Boolean = false,
    var topics: List<Any>? = null,
    var visibility: String = "",
    var forks: Int = -1,
    var open_issues: Int = -1,
    var watchers: Int = -1,
    var default_branch: String = ""
)

data class Links(
    var self: HrefLinks? = null,
    var html: HrefLinks? = null,
    var issue: HrefLinks? = null,
    var comments: HrefLinks? = null,
    var review_comments: HrefLinks? = null,
    var review_comment: HrefLinks? = null,
    var commits: HrefLinks? = null,
    var statuses: HrefLinks? = null
)

data class HrefLinks(
    var href: String = ""
)